providers:
  - tag: "uom.gr"
    name: "Data Dai Virtuoso"
    type: sparql
    url: "http://data.dai.uom.gr:8890/sparql"
    graph_uri: "http://data.dai.uom.gr:8890/CPSV-AP"

#  - tag: "local"
#    name: "Local Virtuoso"
#    type: sparql
#    url: "http://localhost:8080/sparql/"
#    graph_uri: "http://data.dai.uom.gr:8890/CPSV-AP"