openapi: 3.0.3
info:
  title: CPSV Services API
  description: "This is an api aggregator for cpsv compliant public service apis"
  version: 0.1.0
  contact:
    email: apiteam@swagger.io
#   license:
#     name: Apache 2.0
#     url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'http://localhost'
  - url: 'http://localhost:5000'
tags:
  - name: Providers
  - name: Services
paths:
  /providers:
    get:
      tags:
        - Providers
      summary: Returns a list of providers
      description: ""
      operationId: providers
      responses:
        "200":
          description: successful operation
  /services:
    get:
      tags:
        - Services
      summary: Returns a list of public services from every provider
      operationId: services
      responses:
        "200":
          description: successful operation

  /services/{id}:
    get:
      tags:
        - Services
      summary: Returns the details of the service from any providers
      parameters:
        - in: path
          name: id   # Note the name is the same as in the path
          required: true
      operationId: serviceDetails
      responses:
        "200":
          description: successful operation